services:
  postgres:
    build:
      context: ./data-scheme/postgres-18-debian # Контекст сборки
      dockerfile: Dockerfile # Путь к Dockerfile относительно контекста
    container_name: postgres_${ENV:-dev}
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT:-5433}:5432"
    volumes:
      - postgres_data_${ENV:-dev}:/var/lib/postgresql/data
    networks:
      - postgres_network_${ENV:-dev}
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data_dev:
  postgres_data_prod:

networks:
  myjira-network-dev:
    driver: bridge
  myjira-network-prod:
    driver: bridge